select L3.COMPANY_NAME as BRANCH_NAME, L3.COMPANY_NAME_E as BRANCH_NAME_E,
       L2.COMPANY_NAME as COMPANY_NAME, L2.COMPANY_NAME_E as COMPANY_NAME_E,L2.FOOTER as COMPANY_FOOTER,
       L1.COMPANY_NAME as MAIN_COMPANY_NAME, L1.COMPANY_NAME_E as MAIN_COMPANY_NAME_E,
       L2.LOGO,
		
	   (select USER_NAME_A
	   from $P!{P_SCHEMA_NAME}.SEC_USER
	   where USER_ID = $P{P_USER_ID} ) as WORKSPACE,
	   
		case when to_number($P{P_INVOICE_TYPE}) in(21, 22) then 'فاتورة مشتريات ضريبية /Tax Purchase Invoice '
		else 'فاتورة ضريبية /Tax Invoice '
		end as INVOICE_TITLE,
		L2.COMPANY_DESCRIPTION1 as ADDRESS,
		 L2.VAT_NO  as  COMP_VAT_NO,
		L2.COMMERCE_REGISTER,
		SETTING_COMPANY.SV as SHOW_MAIN_COMPANY
     
from 
	$P!{P_SCHEMA_NAME}.COMPANY_INFO L3
		cross join(
		select
				SETTING_VALUE SV
			from
				$P!{P_SCHEMA_NAME}.APP_GENERAL_SETTINGS_DTL
				
			where
				CATEGORY_NO = 1000
				and SETTING_KEY = 11
	) SETTING_COMPANY
	inner join $P!{P_SCHEMA_NAME}.COMPANY_INFO L2
	    on L3.MAIN_COMPANY_ID = L2.COMPANY_NO
	inner join $P!{P_SCHEMA_NAME}.COMPANY_INFO L1
	    on L2.MAIN_COMPANY_ID = L1.COMPANY_NO
where L3.COMPANY_NO = $P{P_APP_COMPANY_NO}