select 
	L2.FOOTER,
	(
	select SEC_USER.USER_NAME_A as USER_NAME
	from $P!{P_SCHEMA_NAME}.SEC_USER
	where  USER_ID =  $P{P_USER_ID}
	) as USER_NAME
	
from 
	$P!{P_SCHEMA_NAME}.COMPANY_INFO L3
	inner join $P!{P_SCHEMA_NAME}.COMPANY_INFO L2
		on L3.MAIN_COMPANY_ID = L2.COMPANY_NO
	inner join $P!{P_SCHEMA_NAME}.COMPANY_INFO L1
		on L2.MAIN_COMPANY_ID = L1.COMPANY_NO
	inner join $P!{P_SCHEMA_NAME}.INVOICE I
		on L3.COMPANY_NO = I.COMPANY_NO
where	
	I.INVOICE_ID =  $P{P_INVOICE_ID} 
	and I.INVOICE_TYPE =  $P{P_INVOICE_TYPE}