select 
	ID.ITEM_UNIT_ID as ITEM_ID,	
	(case when nvl(I.SERVICE_INVOICE, 'N') = 'N' then  IT.ITEM_NAME else ID.ITEM_NAME end
	|| nvl2(IB.ITEM_BARCODE_NOTE, ' - ' || IB.ITEM_BARCODE_NOTE, '')) || case when ID.NOTES is not null then chr(10) ||
	'ملاحظة : ' || ID.NOTES end
	as ITEM_NAME,
	U.UNIT_NAME as UNIT_NAME,
	ID.QUANTITY as QUANTITY,
	ID.FREE_QUANTITY as FREE_QUANTITY,
	ID.UNIT_PRICE as UNIT_PRICE,
	ID.DISCOUNT as DISCOUNT,
	ID.END_PRICE as END_PRICE,
	row_number() over (order by ID.INVOICE_DTL_INDEX) as INVOICE_DTL_INDEX,
	IU.UNIT_QUANTITY
from 
	$P!{P_SCHEMA_NAME}.INVOICE_DTL ID
	left join $P!{P_SCHEMA_NAME}.INVOICE I
		on ID.INVOICE_ID = I.INVOICE_ID
		and ID.INVOICE_TYPE = I.INVOICE_TYPE
	left join $P!{P_SCHEMA_NAME}.ITEM_UNIT IU
		on ID.ITEM_UNIT_ID = IU.ITEM_UNIT_ID
		and IU.COMPANY_NO = ID.SUB_COMPANY_NO
	left join $P!{P_SCHEMA_NAME}.ITEM IT
		on IU.ITEM_ID = IT.ITEM_ID
		and IU.COMPANY_NO = IT.COMPANY_NO
	left join $P!{P_SCHEMA_NAME}.UNIT U
		on IU.UNIT_ID = U.UNIT_ID
	left join ( 
				select ITEM_UNIT_ID, max(ITEM_BARCODE) as ITEM_BARCODE, NOTE as ITEM_BARCODE_NOTE, COMPANY_NO 
				from $P!{P_SCHEMA_NAME}.ITEM_BARCODE
				group by ITEM_UNIT_ID, NOTE, COMPANY_NO 
			) IB 
		on IB.ITEM_UNIT_ID = IU.ITEM_UNIT_ID 
		and IB.COMPANY_NO = IU.COMPANY_NO 
		and IB.ITEM_BARCODE = ID.ITEM_BARCODE

where 
	I.INVOICE_ID = $P{P_INVOICE_ID}
	and I.INVOICE_TYPE = $P{P_INVOICE_TYPE}
order by 
	ID.INVOICE_DTL_INDEX